### PR TITLE
Platta deployment issues

### PR DESCRIPTION
**Pull request by terovirtanen**
* Openshift write access for pycache

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service.-pr30.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service.-pr30.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service.-pr30.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service.-pr30.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service.-pr30.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service.-pr30.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr30.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr30.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr30.api.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
