### PR TITLE
doc: openapi documentation, initial commit

### PR DESCRIPTION
**Pull request by jammi**
Manually crafted openapi documentation and associated tooling.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr79.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — COMMENTED** [review]
I noticed we're maintaining the API documentation manually. Could we revisit this decision and consider using drf-spectacular instead? I understand there might have been reasons for the current approach, but I'm concerned about the long-term maintainability and consistency of manually written docs. In my experience, focusing on accurate input/output structures is crucial, and drf-spectacular excels at that.

Why wasn't the drf-spectacular good enough to create the OpenAPI docs? What were the reasons behind the decision that we would be maintaining the docs manually? I think that the most important thing in API documentation is the structure of input and output. To be more specific, the fields and their types and supported formats. The response types are secondary and they usually are quite predictable. I mean, even if an error case would be undocumented, I can expect that the endpoint can still respond with an error.

The DRF-spectacular has been in use in several city of Helsinki projects, for example in Kukkuu and LinkedEvents and it has served well enough, as far as I know.

I used a couple of prompts with Google Gemini (week or 2 back) and got this as an result: https://github.com/City-of-Helsinki/notification-service-api/tree/gemini-spectacular. It is not fully ready, but it shows that the spectacular generated OpenAPI configuration yamls, Swagger UI and Redoc, and to me they look good enough.

https://github.com/user-attachments/assets/074e8885-a6b1-4d08-8227-c1aa17e0d749

Conventional commit note: We have been using "docs" as a prefix for documentation commits, as recommended in conventional commit spec https://www.conventionalcommits.org/en/v1.0.0/#specification.

**Comment by nikomakela** [comment]
If the example branch that I gave does not resolve the issues that you found and the open api doc is a must have, sure we can go forward with this one too, but since the other teams are using the spectacular already, I guess they will ask the same questions. The notification service has not changed much during the years and probably won't change much in coming years either, so the documentation might not have any up-to-dateness issues.

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr79.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by jakezu** [comment]
> If the example branch that I gave does not resolve the issues that you found and the open api doc is a must have, sure we can go forward with this one too, but since the other teams are using the spectacular already, I guess they will ask the same questions. The notification service has not changed much during the years and probably won't change much in coming years either, so the documentation might not have any up-to-dateness issues.

Yes, we’ve discussed this with Jiri and Jammi a couple of times, and given that we don’t have the resources to approach it differently, this works for now. There might also be an opportunity to revisit and adjust this later.

**Comment by jammi** [comment]
@nikomakela The issue with drf-spectacular is that it's not automatic nor does it really save any time. It adds complications and would require editing the source anyway. I spent way more time with trying to make it work, yet manually crafting the openapi was a fraction of the work, and drf-spectacular never produced as good results. Once the drf-spectacular attempt got complex enough to break functionality, I started anew with what I had learned and left the branch without a pull request in place, because it doesn't really serve as API documentation.

Part of the issue is that neither the framework used or the language used in this project is dynamically typed, so the source code itself isn't helpful, instead you'd have to scatter nonstandard schema syntaxes and try to document what each property means using specacular-specific syntax, and it's never as good as the standard syntax of json-schema and the API specification on the top level structure of openapi in manual form.

Using OpenAPI as a validation layer in front of Django in the form of a validating proxy using prism or some other product however would simplify the Django code itself, because you'd not need defensive programming trying to protect from improper API use.

OpenAPI can also be generated into client API libraries for all kinds of clients starting with various web framework clients, or ones for end-to-end testing and such. Redoc is a cool multi-tool that could provide such client compilation, and it can build a validator and prettier documentation than swagger-tools.

The reason to go with openapitools/openapi-validator and swagger-ui instead of redoc however was the ease of setup. They work out of the box as contairerized apps and redoc doesn't; instead it's pretty complex and either requires to build your own dockerized thing from scratch, because their business model is selling such as a service. I also didn't feel like complicating the source code or repository dependencies by requiring locally installed packages.

**Review by jakezu — APPROVED** [review]

**Pull request merged**
