### PR TITLE
Upgrade dependencies and pre-commit hooks

### PR DESCRIPTION
**Pull request by nikomakela**
NS-11 NS-31 NS-32 NS-33 NS-34.

NOTE: The required pipeline changes are in https://dev.azure.com/City-of-Helsinki/kuva-notification-service-api/_git/kuva-notification-service-api-pipelines/pullrequest/9859. **If these are not applied, the static tests might fail.**

**Install the new pre-commit hooks with `pre-commit install`.**

1. Replace Black, Flake8 and Isort with Ruff.
2. Update the pre-commit -hook to use `Ruff` for code formatting and `Conventional-pre-commit` and `Gitlint` to check the commit message.
3. Upgrade the dependencies.
4. Improve the `.env.example` file to contain all the necessary variables
5. Improve the `docker-compose` configuration to use `DOCKER_TARGET` variable to define the target (development/production).
6. **IMPORTANT for SECURITY: Remove the CREATE_SUPERUSER environment variable**
7. Removed the deprecated and unused file storage configurations.
8. Removed the deprecated USE_L10N setting.
9. Upgrade the Postgres to v13

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr40.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by nikomakela** [comment]
NOTE: the static tests are now failing because https://dev.azure.com/City-of-Helsinki/kuva-notification-service-api/_git/kuva-notification-service-api-pipelines/pullrequest/9859 needs to be applied first.

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr40.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr40.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr40.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr40.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr40.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by jammi** [comment]
Seems fine to me, but there are a couple of deprecation warnings and test file permission errors when run in the container, and IIRC, these aren't newly introduced:
```
../opt/app-root/lib64/python3.11/site-packages/django/conf/__init__.py:267
  /opt/app-root/lib64/python3.11/site-packages/django/conf/__init__.py:267: RemovedInDjango50Warning: The USE_L10N setting is deprecated. Starting with Django 5.0, localized formatting of data will always be enabled. For example Django will display numbers and dates using the format of the current locale.
    warnings.warn(USE_L10N_DEPRECATED_MSG, RemovedInDjango50Warning)

../opt/app-root/lib64/python3.11/site-packages/django/conf/__init__.py:278
  /opt/app-root/lib64/python3.11/site-packages/django/conf/__init__.py:278: RemovedInDjango51Warning: The DEFAULT_FILE_STORAGE setting is deprecated. Use STORAGES instead.
    warnings.warn(DEFAULT_FILE_STORAGE_DEPRECATED_MSG, RemovedInDjango51Warning)

../opt/app-root/lib64/python3.11/site-packages/_pytest/cacheprovider.py:451
  /opt/app-root/lib64/python3.11/site-packages/_pytest/cacheprovider.py:451: PytestCacheWarning: could not create cache path /app/.pytest_cache/v/cache/nodeids: [Errno 13] Permission denied: '/app/.pytest_cache'
    config.cache.set("cache/nodeids", sorted(self.cached_nodeids))

../opt/app-root/lib64/python3.11/site-packages/_pytest/stepwise.py:56
  /opt/app-root/lib64/python3.11/site-packages/_pytest/stepwise.py:56: PytestCacheWarning: could not create cache path /app/.pytest_cache/v/cache/stepwise: [Errno 13] Permission denied: '/app/.pytest_cache'
    session.config.cache.set(STEPWISE_CACHE_DIR, [])

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

**Review by jammi — APPROVED** [review]
👍

**Comment by nikomakela** [comment]
> Seems fine to me, but there are a couple of deprecation warnings and test file permission errors when run in the container, and IIRC, these aren't newly introduced:
> ```
> ../opt/app-root/lib64/python3.11/site-packages/django/conf/__init__.py:267
>   /opt/app-root/lib64/python3.11/site-packages/django/conf/__init__.py:267: RemovedInDjango50Warning: The USE_L10N setting is deprecated. Starting with Django 5.0, localized formatting of data will always be enabled. For example Django will display numbers and dates using the format of the current locale.
>     warnings.warn(USE_L10N_DEPRECATED_MSG, RemovedInDjango50Warning)
> 
> ../opt/app-root/lib64/python3.11/site-packages/django/conf/__init__.py:278
>   /opt/app-root/lib64/python3.11/site-packages/django/conf/__init__.py:278: RemovedInDjango51Warning: The DEFAULT_FILE_STORAGE setting is deprecated. Use STORAGES instead.
>     warnings.warn(DEFAULT_FILE_STORAGE_DEPRECATED_MSG, RemovedInDjango51Warning)
> 
> ../opt/app-root/lib64/python3.11/site-packages/_pytest/cacheprovider.py:451
>   /opt/app-root/lib64/python3.11/site-packages/_pytest/cacheprovider.py:451: PytestCacheWarning: could not create cache path /app/.pytest_cache/v/cache/nodeids: [Errno 13] Permission denied: '/app/.pytest_cache'
>     config.cache.set("cache/nodeids", sorted(self.cached_nodeids))
> 
> ../opt/app-root/lib64/python3.11/site-packages/_pytest/stepwise.py:56
>   /opt/app-root/lib64/python3.11/site-packages/_pytest/stepwise.py:56: PytestCacheWarning: could not create cache path /app/.pytest_cache/v/cache/stepwise: [Errno 13] Permission denied: '/app/.pytest_cache'
>     session.config.cache.set(STEPWISE_CACHE_DIR, [])
> 
> -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
> ```

Those deprecations should have been tackled with 2 commits in this PR already. So, I guess you just didn't have the freshest container image?

But, those permission issues I haven't fixed yet, so I could fix those in this PR still.

- [ ] Fix the Ruff writing permission issue in dockerized env.

**Comment by nikomakela** [comment]
> Seems fine to me, but there are a couple of deprecation warnings and test file permission errors when run in the container, and IIRC, these aren't newly introduced:

Okay, I think I now understand why this happened. I got the old content in my docker VOLUME also! So, the thing is that the volume that stores the files does not get refreshed during the build. Because of that, you migth have a brand new shining Django container, but the files inside it are still the old ones! 😞 After I removed my old volume (created 3 days ago), the deprecation messages are now gone.

The docker-compose is having these for the django data, which we usually haven't had: 
```

services:
  django:
    volumes:
      - djangodata:/app

volumes:
  djangodata:
    driver: local
```

If you do not want to preserve data from previous runs, run `docker compose down -v -f` before bringing the containers up again.

**Pull request merged**
