### PR TITLE
build(deps): upgrade all the requirements

### PR DESCRIPTION
**Pull request by nikomakela**
NS-11.

Used `pip-compile -U [requirement-file]` to upgrade the requirements. Now the Django is upgraded to v5!

Removed the `django-ilmoitin`.

> The django-ilmoitin is not used in the notification service, but it was
still installed as an dependency. It also cascaded to multiple other big
dependencies like django-mailer, django-anymail, django-parler, jinja2
and markupsafe. None of those are really needed.

NOTE: The related environment variables are removed from the pipeline configuration in this PR https://dev.azure.com/City-of-Helsinki/kuva-notification-service-api/_git/kuva-notification-service-api-pipelines/pullrequest/9889.

### CODE REVIEW

**Review by jammi — APPROVED** [review]
Works for me.

**Comment by karisal-anders** [comment]
Running pytest in container fails:
```bash
FAILED api/tests/test_api.py::test_send_sms_unauthentication - ImportError: Module "django.contrib.sessions.serializers" does not define a "PickleSerializer" attribute/class
FAILED api/tests/test_api.py::test_send_sms - ImportError: Module "django.contrib.sessions.serializers" does not define a "PickleSerializer" attribute/class
FAILED api/tests/test_api.py::test_webhook_delivery_log - ImportError: Module "django.contrib.sessions.serializers" does not define a "PickleSerializer" attribute/class
FAILED api/tests/test_api.py::test_get_delivery_log_unauthenticated_or_unauthorized - ImportError: Module "django.contrib.sessions.serializers" does not define a "PickleSerializer" attribute/class
FAILED api/tests/test_api.py::test_get_delivery_log - ImportError: Module "django.contrib.sessions.serializers" does not define a "PickleSerializer" attribute/class
```

**Comment by nikomakela** [comment]
@jammi Thanks for reviewing earlier, but I'm not requesting a renewed review, since I'm now removing the dependency to django-ilmoitin and the configurations related to django-mailer and anymail that cascaded from django-ilmoitin.

**Comment by nikomakela** [comment]
NOTE: The tests were failing because the quota limit was reached. I removed some old pods (that shouold have already been deleted) and now the pipeline should have enough quota resources again.

**Review by karisal-anders — APPROVED** [review]

**Pull request merged**
