### PR TITLE
NS-165 | Add prune_delivery_log & prune_django_admin_log management commands

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat: add prune_(delivery_log|django_admin_log) management commands

refs NS-165

## Related

[NS-165](https://helsinkisolutionoffice.atlassian.net/browse/NS-165)

[NS-165]: https://helsinkisolutionoffice.atlassian.net/browse/NS-165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### `prune_delivery_log` help
```
usage: manage.py prune_delivery_log [-h] [--months MONTHS] [--dry-run] [--version] [-v {0,1,2,3}] [--settings SETTINGS]
                                    [--pythonpath PYTHONPATH] [--traceback] [--no-color] [--force-color] [--skip-checks]

Remove old delivery logs (i.e. api.DeliveryLog objects)

options:
  -h, --help            show this help message and exit
  --months MONTHS       Number of months to keep logs. Default is 6 months
  --dry-run             Dry run mode i.e. don't commit changes, but show what would be done
  --version             Show program's version number and exit.
  -v {0,1,2,3}, --verbosity {0,1,2,3}
                        Verbosity level; 0=minimal output, 1=normal output, 2=verbose output, 3=very verbose output
  --settings SETTINGS   The Python path to a settings module, e.g. "myproject.settings.main". If this isn't provided, the
                        DJANGO_SETTINGS_MODULE environment variable will be used.
  --pythonpath PYTHONPATH
                        A directory to add to the Python path, e.g. "/home/djangoprojects/myproject".
  --traceback           Raise on CommandError exceptions.
  --no-color            Don't colorize the command output.
  --force-color         Force colorization of the command output.
  --skip-checks         Skip system checks.
```

### `prune_django_admin_log` help
```
usage: manage.py prune_django_admin_log [-h] [--months MONTHS] [--dry-run] [--version] [-v {0,1,2,3}] [--settings SETTINGS]
                                        [--pythonpath PYTHONPATH] [--traceback] [--no-color] [--force-color] [--skip-checks]

Remove old Django admin logs (i.e. admin.LogEntry objects)

options:
  -h, --help            show this help message and exit
  --months MONTHS       Number of months to keep logs. Default is 60 months
  --dry-run             Dry run mode i.e. don't commit changes, but show what would be done
  --version             Show program's version number and exit.
  -v {0,1,2,3}, --verbosity {0,1,2,3}
                        Verbosity level; 0=minimal output, 1=normal output, 2=verbose output, 3=very verbose output
  --settings SETTINGS   The Python path to a settings module, e.g. "myproject.settings.main". If this isn't provided, the
                        DJANGO_SETTINGS_MODULE environment variable will be used.
  --pythonpath PYTHONPATH
                        A directory to add to the Python path, e.g. "/home/djangoprojects/myproject".
  --traceback           Raise on CommandError exceptions.
  --no-color            Don't colorize the command output.
  --force-color         Force colorization of the command output.
  --skip-checks         Skip system checks.
```

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr71.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr71.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr71.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr71.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr71.api.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
