### PR TITLE
Improvements to notification service message logs admin

### PR DESCRIPTION
**Pull request by nikomakela**
NS-161.

- Search with report text or user email
- Show more columns in list view
- Filter with message status and created at date
- Ordering set to descending created at

image

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr60.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr60.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr60.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by jakezu** [comment]
LGFM

**Review by jakezu — APPROVED** [review]
LGFM

**Comment by terovirtanen** [comment]
**Notification service branch is deployed to platta: https://kuva-notification-service-pr60.api.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
